### ISSUE TITLE
Not a real issue, Chat-GPT doesn't thinks you generate clickbait, lol

### ISSUE THREAD

**Issue by zardilior** [cbrgm/clickbaiter#6]
<img width="756" alt="Screen Shot 2023-01-28 at 9 16 12" src="https://user-images.githubusercontent.com/8218137/215274425-e0fce265-f355-4606-b992-b7a2cadb85b1.png">

**Comment by cbrgm** [comment]
Well,  finally this project has fulfilled its purpose. Thank you for sharing! 😂
